import Head from 'next/head'
import Headers from '../components/Headers'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/request'

export default function Home(requests) {
  return (
    <div className=''>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <Headers />

      <Nav />

      <Results request={requests} />

    </div>
  )
}


export async function getServerSideProps(context) {
  const genre = context.query.find

  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)
    .then(res => res.json())

  return {
    props: {
      request: request.results
    }
  }
}