import { GetServerSideProps } from 'next';
import Head from 'next/head';
import Headers from '../components/Headers';
import Nav from '../components/Nav';
import Results from '../components/Results';
import { RequestProps } from '../components/_shared/types';
import requests from '../utils/request';

export default function Home(results: Record<'results', RequestProps[]>) {
	const data = results.results;
	return (
		<div className=''>
			<Head>
				<title>Hulu</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Headers />

			<Nav />

			<Results results={data} />
		</div>
	);
}

export const getServerSideProps: GetServerSideProps = async (context) => {
	const genre = context.query.find;

	const request = await fetch(
		`https://api.themoviedb.org/3${requests.fetchTrending.url}`
	)
		.then((res) => res.json())
		.catch((err) => console.log(err));

	return {
		props: {
			results: request.results,
		},
	};
};
