import { GetServerSideProps } from 'next';
import Head from 'next/head';
import Headers from '../components/Headers';
import Nav from '../components/Nav';
import Results from '../components/Results';
import requests from '../utils/request';

export default function Home(results: Record<'results', RequestProps[]>) {
	console.log(results);
	const data = results.results;
	return (
		<div className=''>
			<Head>
				<title>Hulu</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Headers />

			<Nav />

			<Results results={data} />
		</div>
	);
}

export interface RequestProps {
	adult: boolean;
	backdrop_path: string;
	genre_ids: number[];
	id: number;
	media_type: string;
	original_language: string;
	original_title: string;
	overview: string;
	popularity: number;
	poster_path: string;
	release_date: string;
	title: string;
	video: boolean;
	vote_average: number;
	vote_count: number;
}

export const getServerSideProps: GetServerSideProps = async (context) => {
	const genre = context.query.find;

	const request = await fetch(
		`https://api.themoviedb.org/3${requests.fetchTrending.url}`
	)
		.then((res) => res.json())
		.catch((err) => console.log(err));

	return {
		props: {
			results: request.results,
		},
	};
};
